# Add 'documentation' label to any md file changes
  documentation:
    - ./*.md

# Add '@domain/core' label to any change within the 'core' package
  core:
    - ./src/**/*.ts

# Add 'test' label to any change to *.spec.js files within the source dir
  test:
    - src/**/*.spec.js

# Add 'build' label to any change webpack.config.ts
  build:
    - webpack.config.ts

# Add 'workflow' label to any change webpack.config.ts
  workflow:
    - .github/**/*

