name: NPM Publish

# Controls when the action will run.
on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      # clean install of your projects' deps. We use "npm ci" to avoid package lock changes
      - run: npm ci
      # update npm registry
      - run: npm set registry https://registry.npmjs.org/
      # NOTE set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global tech.email "tech.rubicone@gmail.com"
      # NOTE upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # push the version changes to GitHub
      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
